class State():
    PARKED="PARKED"
    WAITING="WAITING"
    CROSSING="CROSSING"
    DESTROYED="DESTROYED"
    
class Direction():
    RIGHT="RIGHT"
    LEFT="LEFT"
    NONE="NONE"
    
    
class Priority():
    NONE=0
    DIREITA_ESQUERDA=1
    ESQUERDA_DIREITA=2
    
    
BRIDGE_LEFT_OFFSET=220
BRIDGE_RIGHT_OFFSET=815