class State():
    PARKED="PARKED"
    WAITING="WAITING"
    CROSSING="CROSSING"
    DESTROYED="DESTROYED"
    IN_LINE="IN_LINE"
    
class Direction():
    RIGHT="RIGHT"
    LEFT="LEFT"
    
class Priority():
    RIGHT="RIGHT"
    LEFT="LEFT"
    NONE="NONE"
    
    
BRIDGE_LEFT_OFFSET=408#220
BRIDGE_RIGHT_OFFSET=1000#815